# Generated by Django 5.1.1 on 2024-10-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_summary_on_self_alter_summary_owed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='owed',
        ),
    ]
