# Generated by Django 5.2.4 on 2025-07-08 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
    ]
