// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkeixiglbteyjzjnizix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrZWl4aWdsYnRleWp6am5peml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjI5MjMsImV4cCI6MjA2NzE5ODkyM30.mBPnWFpuFaRGtLGxhsRFW6822BuDBr01kFQwunpjOXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});