# Generated by Django 4.2.23 on 2025-07-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_leaveapplication_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='description',
        ),
    ]
